openapi: "3.0.0"

info:
  title: Test Schema References
  description: API to illustrate the OpenAlchemy $ref feature for a column.
  version: "0.1"

paths:
  /employee:
    get:
      summary: Used to retrieve all employees
      responses:
        200:
          description: Return all employees from the database.
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/Employee"

components:
  schemas:
    Id:
      type: integer
      description: Unique identifier for the employee.
      example: 0
      x-primary-key: true
    Name:
      type: string
      description: The name of the employee.
      example: David Andersson
    Division:
      type: string
      description: The part of the company the employee works in.
      example: Engineering
    Employee:
      description: Person that works for a company.
      type: object
      x-tablename: employee
      properties:
        id:
          $ref: "#/components/schemas/Id"
        name:
          $ref: "#/components/schemas/Name"
        division:
          $ref: "#/components/schemas/Division"